### model
model_name_or_path: /lustre/S/huangdi/open_for_out/models/deepseek-coder-6.7b-instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: apps_train
template: deepseekcoder
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/deepseek-coder-6.7b-instruct-apps-llamafactory-1205
logging_steps: 1
save_steps: 3000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 16
learning_rate: 2.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_steps: 25
bf16: true
ddp_timeout: 180000000
seed: 42
optim: adamw_torch

